import os
import logging
from datetime import datetime, timezone

from .neo4j_client import get_driver

logger = logging.getLogger(__name__)


def _query_active_permits_for_asset(asset_id: str):
    try:
        drv = get_driver()
        if not drv:
            return []
        with drv.session() as session:
            q = (
                "MATCH (perm:Permit)-[:APPLIES_TO]->(a:Asset {id:$asset}) RETURN perm LIMIT 5"
            )
            res = session.run(q, asset=asset_id)
            return [record["perm"] for record in res]
    except Exception:
        logger.exception("Neo4j query failed")
        return []


def _normalize_labels(detections):
    labels = []
    for d in detections:
        if not isinstance(d, dict):
            continue
        label = d.get("label") or d.get("class") or d.get("name")
        if label:
            labels.append(str(label).lower())
    return labels


def _contains_required_ppe(labels, required_labels):
    for label in labels:
        for required in required_labels:
            if required in label:
                return True
    return False


def evaluate_composite_risk(source: str, payload: dict) -> dict:
    """A first-pass deterministic composite risk evaluator.

    Rules (scaffold):
    - vision: PPE or unsafe detection increases risk
    - sensor: gas sensor anomaly adds 0.6
    - any active permit on same asset adds 0.3
    - compound multipliers increase score for combinations
    """
    # Start with a small baseline risk rather than 0 so the UI doesn't look broken
    base = 0.15
    factors = []

    source_lower = source.lower() if isinstance(source, str) else ""
    payload_source = str(payload.get("source", "")).lower()

    # Vision rules
    if source_lower in ["vision", "user"] or payload_source in ["vision", "user"]:
        detections = payload.get("detections", []) or []
        labels = _normalize_labels(detections)
        required = [x.strip().lower() for x in os.getenv("PPE_REQUIRED_LABELS", "helmet,hardhat,vest,safety vest").split(",") if x.strip()]
        hazard_labels = [x.strip().lower() for x in os.getenv("HAZARD_LABELS", "person,worker,man,woman").split(",") if x.strip()]
        # Prefer deterministic PPE summary generated by vision worker if present
        ppe_summary = payload.get("ppe") or {}
        if isinstance(ppe_summary, dict) and ppe_summary:
            if not ppe_summary.get("ppe_ok", True):
                base += 0.45
                factors.append({"type": "PPE Summary Violation", "detail": ppe_summary})
        else:
            if labels:
                if any(d.get("ppe_violation") for d in detections if isinstance(d, dict)):
                    base += 0.4
                    factors.append({"type": "PPE Violation", "detail": detections})
                elif any(h in label for label in labels for h in hazard_labels) and not _contains_required_ppe(labels, required):
                    base += 0.4
                    factors.append({"type": "PPE Missing", "labels": labels, "required": required})

    # Sensor rules
    if source_lower in ["sensor", "user"] or payload_source in ["sensor", "user"]:
        val = None
        # Check for value at top level and also nested in payload
        raw_val = payload.get("value")
        if raw_val is None and isinstance(payload.get("payload"), dict):
            raw_val = payload["payload"].get("value")
        if raw_val is not None:
            try:
                val = float(raw_val)
            except Exception:
                val = None
        
        sensor_id = payload.get("sensor_id") or ""
        metadata = payload.get("metadata") or {}
        # Also check nested payload for type (from UI form)
        nested = payload.get("payload") if isinstance(payload.get("payload"), dict) else {}
        sensor_type = str(payload.get("type") or nested.get("type") or metadata.get("type") or "").lower()
        if not sensor_id and nested:
            sensor_id = nested.get("sensor_id", "")

        if "gas" in sensor_id.lower() or "gas" in sensor_type:
            gas_threshold = float(os.getenv("GAS_THRESHOLD", 50.0))
            if val is not None:
                if val > gas_threshold:
                    excess_ratio = (val - gas_threshold) / gas_threshold
                    base += min(1.0, 0.6 + (excess_ratio * 0.4))
                    factors.append({"type": "Gas Anomaly", "value": val, "threshold": gas_threshold})
                elif val > (gas_threshold * 0.4):
                    escalation = (val - (gas_threshold * 0.4)) / (gas_threshold * 0.6)
                    base += (escalation * 0.45)
                    factors.append({"type": "Elevated Gas", "value": val, "threshold": gas_threshold})
        elif "temperature" in sensor_id.lower() or "temperature" in sensor_type:
            temp_threshold = float(os.getenv("TEMP_THRESHOLD", 45.0))
            if val is not None:
                if val > temp_threshold:
                    excess_ratio = (val - temp_threshold) / temp_threshold
                    base += min(1.0, 0.4 + (excess_ratio * 0.6))
                    factors.append({"type": "Temperature Anomaly", "value": val, "threshold": temp_threshold})
                elif val > (temp_threshold * 0.7):
                    escalation = (val - (temp_threshold * 0.7)) / (temp_threshold * 0.3)
                    base += (escalation * 0.3)
                    factors.append({"type": "Elevated Temperature", "value": val, "threshold": temp_threshold})
        elif "pressure" in sensor_id.lower() or "pressure" in sensor_type:
            pressure_threshold = float(os.getenv("PRESSURE_THRESHOLD", 100.0))
            if val is not None and val > pressure_threshold:
                excess_ratio = (val - pressure_threshold) / pressure_threshold
                base += min(1.0, 0.5 + (excess_ratio * 0.5))
                factors.append({"type": "Pressure Anomaly", "value": val, "threshold": pressure_threshold})

    # Permit proximity / asset rules
    asset_id = None
    if payload.get("asset"):
        asset_id = payload.get("asset") if isinstance(payload.get("asset"), str) else payload.get("asset").get("id")
    # fallback: camera name may map to asset id in some deployments
    if not asset_id and payload.get("camera"):
        asset_id = payload.get("camera")

    if asset_id:
        permits = _query_active_permits_for_asset(asset_id)
        if permits:
            base += 0.3
            factors.append({"type": "Active Permit", "asset": asset_id, "count": len(permits)})

    # Compound Risk Detection Engine (Hackathon Alignment)
    # Detect Hot Work Permit + Elevated Gas Readings
    types = [f.get("type") for f in factors]
    permit_type = str(payload.get("permit_type") or payload.get("metadata", {}).get("permit_type") or "").lower()
    is_hot_work = any(p.get("type", "").lower() == "hot work" for p in permits) if asset_id and permits else permit_type == "hot work"
    
    if "Gas Anomaly" in types and ("Active Permit" in types or is_hot_work):
        if is_hot_work:
            base = 1.0  # Immediate critical risk for Hot Work + Gas
            factors.append({"type": "Compound Risk: Hot Work + Gas", "detail": "CRITICAL FATALITY RISK - Visakhapatnam Scenario Detected"})
        else:
            base = min(1.0, base + 0.3)
            factors.append({"type": "Compound Risk: Gas+Permit", "detail": "escalation"})

    # Additional rules (enrichment for future ML)
    # Crowding detection: if vision detects multiple persons and no permit
    if source == "vision":
        detections = payload.get("detections", []) or []
        person_count = sum(1 for d in detections if isinstance(d, dict) and "person" in (d.get("label") or "").lower())
        if person_count >= 3:
            crowd_threshold = float(os.getenv("CROWD_THRESHOLD", "0.1"))
            base += crowd_threshold
            factors.append({"type": "Crowd Detected", "persons": person_count})

        # Motion anomaly: high confidence detections in restricted zones
        high_confidence = sum(1 for d in detections if isinstance(d, dict) and d.get("confidence", 0) > 0.85)
        if high_confidence > len(detections) * 0.7 and payload.get("zone") == "restricted":
            base += 0.15
            factors.append({"type": "Motion in Restricted Zone", "detail": "high confidence detections"})

    # Confined space flag if labeled
    is_confined = payload.get("confined_space") or (payload.get("metadata") or {}).get("location_type") == "confined"
    if is_confined:
        confined_multiplier = float(os.getenv("CONFINED_SPACE_MULTIPLIER", "1.2"))
        base = min(1.0, base * confined_multiplier)
        factors.append({"type": "Confined Space", "multiplier": confined_multiplier})

    # Compound Risk: Confined Space Entry + Abnormal Process
    abnormal_process = payload.get("abnormal_process") or "Gas Anomaly" in types
    if is_confined and abnormal_process:
        base = 1.0
        factors.append({"type": "Compound Risk: Confined Space + Abnormal Process", "detail": "CRITICAL RISK"})

    # Cross-source amplification: vision PPE issue + gas anomaly = high risk
    types = [f.get("type") for f in factors]
    if ("PPE Summary Violation" in types or "PPE Missing" in types) and "Gas Anomaly" in types:
        base = min(1.0, base + 0.25)
        factors.append({"type": "Compound: PPE+Gas", "detail": "critical"})

    # Night shift flag
    if payload.get("shift") == "night":
        base += 0.05
        factors.append({"type": "Night Shift", "detail": "increased baseline"})

    # Clamp
    score = max(0.0, min(1.0, base))
    
    risk_level = "critical" if score > 0.8 else "high" if score > 0.6 else "medium" if score > 0.4 else "low"
    
    reasoning = "Normal operational parameters."
    recommendations = ["Continue standard monitoring."]
    
    if len(factors) > 0:
        reasoning = "Identified risk factors: " + ", ".join([f.get("type", "Unknown") for f in factors]) + "."
        recommendations = []
        if "Gas Anomaly" in types or "Pressure Anomaly" in types or "Temperature Anomaly" in types:
            recommendations.append("Dispatch inspection team to verify sensor integrity.")
        if "Compound Risk: Hot Work + Gas" in types:
            reasoning = "CRITICAL: Imminent fatality risk detected matching Visakhapatnam scenario (Hot Work + Gas)."
            recommendations = ["IMMEDIATELY SUSPEND all hot work permits in zone.", "Evacuate affected area.", "Trigger emergency sirens."]
        if "PPE Missing" in types or "PPE Violation" in types or "PPE Summary Violation" in types:
            recommendations.append("Issue automated warning to zone intercom regarding PPE compliance.")

    return {
        "risk_score": score,
        "risk_level": risk_level,
        "reasoning": reasoning,
        "recommendations": recommendations,
        "factors": factors,
        "evaluated_at": datetime.now(timezone.utc).isoformat() + "Z"
    }
